name: build

on:
  push:
  release:
    types:
      - created
      - edited

jobs:
  xgo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: crazy-max/ghaction-xgo@v1
        with:
          xgo_version: latest
          go_version: 1.18
          dest: builds
          targets: windows/386,windows/amd64,linux/amd64,linux/arm64,darwin/arm64,darwin/amd64
          v: true
          x: false
          race: false
          ldflags: -s -w
          buildmode: default
      - name: Archive
        run: |
          cd builds/github.com/barelyhuman
          for file in $(ls *);
          do 
              tar cfzv "$file".tgz $file
              rm -rf $file
          done
          mv *.tgz ../../..
          cd ../../..
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GH_TOKEN }}
          file: builds/*.tgz
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
